name: Release

on:
  push:
    tags: [ v* ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  create-release:
    if: github.repository_owner == 'openrr'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (linux)
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev libglu1-mesa-dev

      - run: cargo package
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  upload-assets:
    if: github.repository_owner == 'openrr'
    needs: [ create-release ]
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (linux)
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev libglu1-mesa-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: urdf-viz
          archive: $bin-$tag-$target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
